apps/cart/urls.py
from django.urls import path
from apps.cart.views import CartAddView,CartInfoView,CartUpdateView,CartDeleteView
urlpatterns = [
    path('add/',CartAddView.as_view(), name='add'),  # 购物车记录添加
    path('',CartInfoView.as_view(),name='show'),#购物车
    path('update/',CartUpdateView.as_view(),name='update'),#购物车记录更新
    path('delete/',CartDeleteView.as_view(),name='delete'),#购物车记录删除
]

apps/goods/urls.py
from django.urls import path,include
from apps.goods.views import IndexView,DetailView,ListView
urlpatterns = [
    path('index/',IndexView.as_view(),name='index'),#首页
    path('detail/<int:goods_id>',DetailView.as_view(),name='detail'),#商品详情页
    path('list/<int:type_id>/<int:page>',ListView.as_view(),name='list') #商品列表页

]

apps/user/urls.py
from django.urls import path
from apps.user import views
from apps.user.views import RegisterView,ActiveView,LoginView,LogoutView,UserInfoView,UserOrderView,AddressView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    # path('register/',views.register,name='register'),#用户注册
    path('register/',RegisterView.as_view(),name='register'),#用户注册
    path('active/<str:token>',ActiveView.as_view(),name='active'),#用户激活
    path('login/',LoginView.as_view(),name='login'),#用户登录
    path('logout/',LogoutView.as_view(),name='logout'),#用户登出
    # path('send/',views.send)#用户邮件测试

    #用户中心
    #利用login_required()可以实现
    # If the user isn't logged in, redirect to settings.LOGIN_URL, passing the current absolute path in the query string. Example: /accounts/login/?next=/polls/3/.
    # If the user is logged in, execute the view normally. The view code is free to assume the user is logged in.
    # path('',login_required(UserInfoView.as_view()),name='user'),#用户中心-信息页
    # path('order/',login_required(UserOrderView.as_view()),name='order'),#用户中心-订单页
    # path('address/',login_required(AddressView.as_view()),name='address'),#用户中心-地址页
    #使用LoginRequiredMixin类实现
    path('',UserInfoView.as_view(),name='user'),#用户中心-信息页
    path('order/<slug:page>',UserOrderView.as_view(),name='order'),#用户中心-订单页
    path('address/',AddressView.as_view(),name='address'),#用户中心-地址页


    #path('test/',views.user)
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include(('user.urls', 'user'), namespace='user')), #用户模块
    path('cart/',include(('cart.urls', 'cart'), namespace='cart')), #购物车模块
    # path('order/',include(('order.urls','order'),namespace='order')), #订单模块
    path('',include(('goods.urls','goods'),namespace='goods')),#商品模块
    # path('tinymce/', include('tinymce.urls ')),
    path('search/', include('haystack.urls')),#全文搜索
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.urls import reverse
from django.views import View
from django.http.response import JsonResponse
from apps.goods.models import  GoodsSKU
from django_redis import get_redis_connection
# Create your views here.
#添加数据到购物车 ajax
# 如果涉及到数据的修改（新增，更新，删除），采用post
# 如果只涉及数据的获取采用get

#/cart/add
class CartAddView(View):
    '''购物车记录添加'''
    def post(self,request):
        '''
        post请求方式添加购物车
        :param request:
        :return:
        '''
        #首先检验用户是否登录，如果未登录则跳转至登录页面
        user = request.user
        if not user.is_authenticated:
            #用户未登录
            return redirect(reverse('user:login'))
        #接受数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        #数据校验
        #1. 数据完整性
        if not all([sku_id,count]):
            return JsonResponse({"res":1,"errmsg":"数据不完整"})
        #2. 检验添加的商品数目
        try:
            count = int(count)
        except Exception as e:
            #商品数目出错
            return JsonResponse({"res":2,"errmsg":'商品数目出错'})
        #3. 检验商品是否存在
        try:
            sku= GoodsSKU.objects.get(id=sku_id)
        except Exception as e:
            return JsonResponse({"res":3,"errmsg":"商品不存在"})
        #业务处理：添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        #先尝试获取sku_id的值 -》hget cart_key属性
        #如果sku_id在hash中不存在。hget返回None
        cart_count = conn.hget(cart_key,sku_id)
        if cart_count:
            #累加购物车中商品的数目
            count += int(cart_count)
        #检验商品的库存
        print(sku)
        if count > sku.stock:
            #库存不足
            return JsonResponse({'res':4,"errmsg":'商品库存不足'})

        #设置hash中sku_id对应的值
        conn.hset(cart_key,sku_id,count)

        #计算用户购物车中商品的条目数
        total_count = conn.hlen(cart_key)

        #返回应答
        return JsonResponse({'res':5,'total_count':total_count,'message':"添加成功"})

#/cart/
from utils.mixin import LoginRequiredMixin
class CartInfoView(LoginRequiredMixin,View):
    '''购物车页面显示'''
    def get(self,request):
        '''
        显示购物车页面
        :param request:
        :return:
        '''
        #获取登录的用户
        user = request.user

        #获取登录用户的购物车信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        #hgetall()返回一个字典，
        cart_dict = conn.hgetall(cart_key)

        skus = []
        total_count = 0
        total_price = 0
        #遍历获取商品的信息
        for sku_id,count in cart_dict.items():
            #根据商品的id获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)
            #计算商品的小计
            amount = sku.price * int(count)
            # print('amounttype:',type(amount))
            #动态给sku对象加上一个属性amount,保存单个商品的总价
            sku.amount = amount
            # 动态给sku对象加上一个属性count,保存购物车中对应商品的数目
            sku.count = int(count)
            #添加
            skus.append(sku)
            #累加计算商品的总数目和总价格
            total_count += int(count)
            total_price += amount

        context = {
            'total_count': total_count,
            'total_price':total_price,
            'skus':skus
        }
        return render(request,'cart.html',context)

#/cart/update/
#更新购物车记录，采用ajax post,传递参数sku_id,count
class CartUpdateView(View):
    #更新购物车记录
    def post(self,request):

        #首先检验用户是否登录，如果未登录则跳转至登录页面
        user = request.user
        if not user.is_authenticated:
            #用户未登录
            return redirect(reverse('user:login'))
        #接受数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        print('前端发送的数据：',sku_id,count)
        #数据校验
        #1. 数据完整性
        if not all([sku_id,count]):
            return JsonResponse({"res":1,"errmsg":"数据不完整"})
        #2. 检验添加的商品数目
        try:
            count = int(count)
        except Exception as e:
            #商品数目出错
            return JsonResponse({"res":2,"errmsg":'商品数目出错'})
        #3. 检验商品是否存在
        try:
            sku= GoodsSKU.objects.get(id=sku_id)
        except Exception as e:
            return JsonResponse({"res":3,"errmsg":"商品不存在"})
        #4. 检验商品库存
        if count > sku.stock:
            return JsonResponse({'res':4,'errmsg':'商品库存不足'})

        #业务处理
        conn = get_redis_connection('default')
        cart_key = "cart_%d"%user.id
        conn.hset(cart_key,sku_id,count)

        #计算用户购物车中的商品总件数{'1':5,'2':5} 。5+5 = 10
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)
        #返回应答
        return JsonResponse({'res':5,'total_count':total_count,'message':'更新成功'})

#删除购物车数据
#ajax post请求
#前端需要传递的参数，sku_id
#/cart/delete/
class CartDeleteView(View):
    '''购物车记录删除'''
    def post(self,request):
        '''
        post请求
        :param request:
        :return:
        '''
        #验证用户是否登录
        user = request.user
        if not user.is_authenticated:
            #用户未登录
            return JsonResponse({'res':1,'errmsg':'请先登录'})

        #接受数据
        sku_id = request.POST.get('sku_id')
        #校验数据
        if not sku_id:
            #数据不完整
            return JsonResponse({'res':2,'errmsg':'无效的商品id'})
        #检验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res':3,'errmsg':'商品不存在'})

        #业务处理：删除购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        #删除hdel
        conn.hdel(cart_key,sku_id)

        # 计算用户购物车中的商品总件数{'1':5,'2':5} 。5+5 = 10
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        #返回应答
        return JsonResponse({'res':4,'total':total_count,'message':'删除成功'})

templates/base.html
{# 首页，登录，注册 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	{# 网页标题块 #}
    <title>{% block title  %} {% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
    {% block js %} {% endblock %}

</head>
<body>
{#网页顶部欢迎信息块#}
{% block header_on %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
{#					<a href="#">我的订单</a>#}
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{#网页顶部搜索框#}
{% block search_bar %}
    <div class="search_bar clearfix">
		<a href="/index/" class="logo fl"><img src="{% static 'images/logo.png'%}"></a>
		<div class="search_con fl">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
		    </form>
        </div>
		<div class="guest_cart fr">
			<a href="{% url "cart:show"  %} " class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock %}
{#网站主体功能#}
{% block body %}
{% endblock %}
    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{#网页底部html元素块#}
{% block bottom %}
{% endblock %}
{#网页底部引入文件块#}
{% block bottomfiles %}
{% endblock %}
</body>
</html>

templates/base_detail_list.html
{# 详情，列表 #}
{% extends 'base.html' %}
{# 网站主题内容  #}

{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:index' %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
{% block detail_content %} {% endblock %}
{% endblock %}

templates/base_user_center.html
{#用户中心三页面#}
{% extends 'base_no_cart.html' %}
{% load static %}
{% block title %}天天生鲜-用户中心{% endblock %}
{% block pg_title %}用户中心{% endblock %}
{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
                <li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
            </ul>
        </div>
        {% block right_content %}{% endblock %}
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title  %}天天生鲜-首页 {% endblock %}
{% block js %}
   <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock %}

{% block body %}
    <div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

    {# 商品分类栏#}
	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			<li><a href="#" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
        {# 轮播图 #}
		<div class="slide fl">
			<ul class="slide_pics">
                {% for goods in goods_banners %}
				<li><img src="/{{ goods.image }}" alt="{{ goods.sku }}"></li>
			    {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
        {#首页促销活动       #}
		<div class="adv fl">
            {% for pro in promotion_banners %}
{#			<a href="{{ pro.url }}"><img src="/{{ pro.image }}"></a>#}
			<a href="#"><img src="/{{ pro.image }}"></a>
		    {% endfor %}
		</div>
	</div>

    {# 首页分类商品的图片和文字展示信息 #}
    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				<a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/{{ type.image }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="/{{ banner.sku.image }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock %}

{% block bottomfiles %}
{% endblock %}

templates/list.html
{% extends 'base_detail_list.html' %}
{#网页标题#}
{% block title %}
天天生鲜-商品列表
{% endblock %}
{# 列表页详情 #}
{% block detail_content %}
    <div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>
	<div class="main_wrap clearfix">
        <!--新品推荐-->
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for goods in new_skus %}
					<li>
						<a href="{% url 'goods:detail' type.id %}"><img src="/{{ goods.image }}"></a>
						<h4><a href="{% url 'goods:detail' type.id %}">{{ goods.name }}</a></h4>
						<div class="prize">￥{{ goods.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>
        <!--列表页详情信息-->
		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1  %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1  %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1  %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in sku_page %}
				<li>
					<a href="{% url 'goods:detail' type.id %}"><img src="/{{ sku.image }}"></a>
					<h4><a href="{% url 'goods:detail' type.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {# 显示上一页    #}
                {% if sku_page.has_previous %}
				<a href="{% url 'goods:list' type.id sku_page.previous_page_number %}"><上一页</a>
                {% endif %}
                {# 显示页码  #}
                {% for pindex in pages %}
                    {% if pindex == sku_page.number %}
                        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
                {# 显示下一页    #}
				{% if sku_page.has_next %}
				<a href="{% url 'goods:list' type.id sku_page.next_page_number %}">下一页></a>
                {% endif %}
			</div>
		</div>
	    </div>
    </div>


 {% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title  %}天天生鲜-登录 {% endblock %}
{#网页顶部欢迎信息块#}
{% block header_on %}
{% endblock %}
{#网页顶部搜索框#}
{% block search_bar %}
{% endblock %}
{% block body %}
<div class="login_top clearfix">
    <a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
</div>

<div class="login_form_bg">
    <div class="login_form_wrap clearfix">
        <div class="login_banner fl"></div>
        <div class="slogan fl">日夜兼程 · 急速送达</div>
        <div class="login_form fr">
            <div class="login_title clearfix">
                <h1>用户登录</h1>
                <a href="{% url 'user:register' %}">立即注册</a>
            </div>
            <div class="form_input">
                <form method="post">
                    {% csrf_token %}
                    <input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
                    <div class="user_error">输入错误</div>
                    <input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
                    <div class="pwd_error">输入错误</div>
                    <div class="more_input clearfix">
                        <input type="checkbox" name="remember" value="{{ checkbox }}">
                        <label>记住用户名</label>
                        <a href="#">忘记密码</a>
                    </div>

                    <input type="submit" name="" value="登录" class="input_submit">
                </form>

            </div>
        </div>
    </div>
</div>
    {{ status }}
{% endblock %}

templates/order_comment.html
{% extends 'base_user_center.html' %}
{% load static %}
{% block right_content %}
    <div class="right_content clearfix">
        <h3 class="common_title2">订单评价</h3>
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{order.create_time}}</li>
                <li class="col02">订单号：{{order.order_id}}</li>
                <li class="col02 stress">{{order.status_name}}</li>
            </ul>
        <form method="post">
            {% csrf_token %}
            {# 订单id #}
            <input type="hidden" name="order_id" value="{{order.order_id}}">
            {# 订单中有几个商品 #}
            <input type="hidden" name="total_count" value="{{order.order_skus|length}}">
            {% for order_sku in order.order_skus %}
            <table class="order_list_table w980">
                <tbody>
                    <tr>
                        <td width="80%">
                            <ul class="order_goods_list clearfix">
                                <li class="col01"><img src="/{{ order_sku.sku.image }}"></li>
                                <li class="col02">{{order_sku.sku.name}}<em>{{order_sku.price}}/{{order_sku.sku.unite}}</em></li>
                                <li class="col03">{{order_sku.count}}</li>
                            </ul>
                        </td>
                        <td width="20%">{{order_sku.amount}}元</td>
                    </tr>
                </tbody>
            </table>
            <div class="site_con">
                <input type="hidden" name="sku_{{forloop.counter}}" value="{{order_sku.sku.id}}">
                <div class="form_group form_group2">
                    <label>评价内容：</label>
                    <textarea class="site_area" name="content_{{forloop.counter}}"></textarea>
                </div>
            </div>
            {% endfor %}
            <input type="submit" name="" value="提交" class="info_submit">
        </form>
        </div>
{% endblock %}

templates/place_order.html
{% extends 'base_no_cart.html' %}
{% block pg_title %}天天生鲜-提交订单{% endblock %}

{% load static %}
{% block body %}
    <h3 class="common_title">确认收货地址</h3>
	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
            {% for addr in addrs %}

			<dd><input type="radio" name="addr_id" value="{{ addr.id }}" {% if addr.is_default %}checked{% endif  %}>{{ addr.addr }} （{{ addr.receiver }} 收） {{ addr.phone }}</dd>
            {% endfor %}
        </dl>
		<a href="{% url 'user:address' %}" class="edit_site">编辑收货地址</a>

	</div>

	<h3 class="common_title">支付方式</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
            {% csrf_token %}
            <input type="radio" name="pay_style" checked value="0">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="1">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="2">
			<label class="bank">银联支付</label>
            <input type="radio" name="pay_style" value="3">
			<label class="cash">货到付款</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>

	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
		</ul>
        {% for sku in skus %}
        <ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="/{{ sku.image }}"></li>
			<li class="col03">{{ sku.name }}</li>
			<li class="col04">{{ sku.unite }}</li>
			<li class="col05">{{ sku.price }}元</li>
			<li class="col06">{{ sku.count }}</li>
			<li class="col07">{{ sku.amount }}元</li>
		</ul>
        {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>{{ transit_price }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;"  sku_ids ="{{ sku_ids }}" id="order_btn">提交订单</a>
	</div>
{% endblock %}
{#网页底部html元素块#}
{% block bottom %}

	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>

		<div class="mask"></div>
	</div>
{% endblock %}
{#网页底部引入文件块#}
{% block bottomfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
		    //获取用户选择的地址id,支付方式，要购买的商品id字符串
            addr_id = $('input[name="addr_id"]:checked').val();
            pay_method = $('input[name="pay_style"]:checked').val();
            sku_ids = $(this).attr('sku_ids');
            csrf_token = $('input[name="csrfmiddlewaretoken"]').val();

            params = {'addr_id':addr_id,'pay_method':pay_method,'sku_ids':sku_ids,'csrfmiddlewaretoken':csrf_token}
            console.log(params)
            //发送ajax post 请求，访问/order/commit/,传递的参数：addr_id,pay_id,sku_ids,
            $.ajax({
                url:'/order/commit/',
                type:'POST',
                data:params,
                success:function (data) {
                    if (data.res == 5){
                        //更新成功,跳转至个人中心的订单页面；
                        //localStorage.setItem(key,value)：将value存储到key字段
                       localStorage.setItem('order_finish',2);
                        $('.popup_con').fadeIn('fast', function() {
                            setTimeout(function() {
                                $('.popup_con').fadeOut('fast', function () {
                                    window.location.href = '/user/order/1';
                                });
                            },3000)
			         });
                    }else{
                        //更新失败
                        alert('创建失败：'+ data.errmsg)

                    }
                }

            });


		});
	</script>
{% endblock %}

templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% load static %}
{% block right_content %}
<div class="right_content clearfix">
    <div class="info_con clearfix">
    <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
                <li><span>用户名：</span>{{ address.user }}</li>
                {% if address %}
                    <li><span>联系方式：</span>{{ address.phone }}</li>
                    <li><span>联系地址：</span>{{ address.addr }}</li>
                {% else %}
                    <li><span>联系方式：</span>{{ address.phone }}</li>
                    <li><span>联系地址：</span>{{ address.addr }}</li>
                {% endif %}
            </ul>
    </div>

    <h3 class="common_title2">最近浏览</h3>
    <div class="has_view_list">
        <ul class="goods_type_list clearfix">
    {% for goods in goods_li %}
        <li>
        <a href="{% url 'goods:detail' goods.id %}"><img src="/{{ goods.image.url }} "></a>
        <h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
        <div class="operate">
            <span class="prize">￥{{ goods.price }}</span>
            <span class="unit">{{ goods.price }}/{{ goods.unite }}</span>
            <a href="#" class="add_goods" title="加入购物车"></a>
        </div>
    </li>
    {% empty %}
        无历史浏览记录
    {% endfor %}
</ul>
</div>
</div>
{% endblock %}